// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "challenge/alerts/src/api/alerts/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AlertsService is an autogenerated mock type for the AlertsService type
type AlertsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, alert
func (_m *AlertsService) Create(ctx context.Context, alert domain.AlertsDTO) (*domain.Alert, error) {
	ret := _m.Called(ctx, alert)

	var r0 *domain.Alert
	if rf, ok := ret.Get(0).(func(context.Context, domain.AlertsDTO) *domain.Alert); ok {
		r0 = rf(ctx, alert)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Alert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.AlertsDTO) error); ok {
		r1 = rf(ctx, alert)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlertsByType provides a mock function with given fields: ctx, typeInput
func (_m *AlertsService) GetAlertsByType(ctx context.Context, typeInput domain.AlertSearchByTypeDTO) ([]domain.Alert, error) {
	ret := _m.Called(ctx, typeInput)

	var r0 []domain.Alert
	if rf, ok := ret.Get(0).(func(context.Context, domain.AlertSearchByTypeDTO) []domain.Alert); ok {
		r0 = rf(ctx, typeInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Alert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.AlertSearchByTypeDTO) error); ok {
		r1 = rf(ctx, typeInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *AlertsService) GetAll(ctx context.Context) ([]domain.AlertsDTO, error) {
	ret := _m.Called(ctx)

	var r0 []domain.AlertsDTO
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AlertsDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AlertsDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetrics provides a mock function with given fields: ctx
func (_m *AlertsService) GetMetrics(ctx context.Context) ([]domain.Metrics, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Metrics
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Metrics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Metrics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, input
func (_m *AlertsService) Search(ctx context.Context, input domain.AlertSearchDTO) ([]domain.Alert, error) {
	ret := _m.Called(ctx, input)

	var r0 []domain.Alert
	if rf, ok := ret.Get(0).(func(context.Context, domain.AlertSearchDTO) []domain.Alert); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Alert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.AlertSearchDTO) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAlertsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAlertsService creates a new instance of AlertsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAlertsService(t mockConstructorTestingTNewAlertsService) *AlertsService {
	mock := &AlertsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
